language: c
addons:
  homebrew:
    packages:
      - sdl2
      - cmake
os:
  - osx
compiler:
  - clang
  - gcc
script:
  - mkdir build/
  - cd build/
  - cmake -DSDL2_INCLUDE_DIR=/usr/local/include ..
  - make -k
  - ./nothing_test
