dist: trusty
language: c
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - gcc
      - libsdl2-dev
      - libsdl2-mixer-dev
      - xqilla
script:
  - mkdir build/
  - cd build/
  - cmake ..
  - make -k
  - ./nothing_test
  - cd ../levels/
  - make clean
  - make -k
