dist: trusty
language: c
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libsdl2-dev
      - libsdl2-mixer-dev
  homebrew:
    packages:
      - sdl2
      - sdl2_mixer
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - mkdir build/
  - cd build/
  - cmake ..
  - make -k
  - ./nothing_test
  - cd ../levels/
  - make clean
  - make -k
