language: c
addons:
  homebrew:
    packages:
      - sdl2
      - cmake
    update: true
os:
  - osx
compiler:
  - clang
  - gcc
script:
  - mkdir build/
  - cd build/
  - cmake .. -DNOTHING_CI=ON
  - make -k
