dist: xenial
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55/cmake-3.x
    packages:
      - cmake
      - cmake-extras
      - extra-cmake-modules
      - cmake-data
      - libsdl2-dev
      - libsdl2-mixer-dev
      - python3
  homebrew:
    packages:
      - sdl2
      - sdl2_mixer
      - python3
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - mkdir build/
  - cd build/
  - cmake ..
  - make -k
  - ./nothing_test
  - cd ../levels/
  - make clean
  - make -k
