dist: trusty
language: c
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - gcc
      - libsdl2-dev
      - libsdl2-mixer-dev
script:
  - mkdir build/
  - cd build/
  - cmake ..
  - make
