name: CI
on: [push, pull_request]

jobs:
  # TODO(#1176): no clang on linux build on GitHub actions
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev 
      - name: build nothing
        run: |
          ./build-posix.sh 
        env: 
          CC: gcc
          NOTHING_CI: on

  build-macos:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 pkg-config
      - name: build nothing
        run: |
          ./build-posix.sh
        env: 
          CC: clang
          NOTHING_CI: on

  # TODO: build-windows-msvc on GitHub Actions does not support SCU
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: download sdl2
        run: |
          curl -fsSL -o SDL2-devel-2.0.9-VC.zip https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip
          7z x SDL2-devel-2.0.9-VC.zip
          mv SDL2-2.0.9 SDL2
      - name: build nothing
        run: |
          mkdir build
          cd build
          cmake .. -DNOTHING_CI=ON
          cmake --build .
          
  # TODO: %z related warnings on build-windows-mingw GitHub Action
  build-windows-mingw:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this gives us msys.
      - uses: numworks/setup-msys2@v1
      - name: install dependencies
        run: msys2do pacman -S --noconfirm mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-SDL2 make mingw-w64-x86_64-pkg-config
      - name: build nothing
        run: |
          msys2do ./build-posix.sh
        env: 
          CC: gcc
